"""
backend/api/xlsx_style.py — the ONE branded Excel layout, for every export.

The SME workbooks already shipped a premium layout (`sme_export_layouts.py`,
xlsxwriter): a GI logo, a "Report Generated / Generated By" meta band, a merged
navy title bar, coloured headers and framed data. Every OTHER xlsx in the app —
all of `/reports/*` (stock, expiring, movements, PR/PO status…), the master-data
exports, the Man-Hours scorecards, the Executive Summary, the SME session and
overview sheets — came out of `reports.to_xlsx`, which wrote a bare header row
and nothing else.

This module gives that second group the same look, in **openpyxl** (which is
what those call sites already use, so nothing changes hands mid-pipeline). The
geometry is deliberately identical to `sme_export_layouts` so a workbook from
either path is recognisably the same document:

    rows 1-4   logo (left) + right-aligned generated-at / generated-by meta
    row  5     merged title bar — scheme title_bg, white bold 13pt
    row  6     header row — scheme header_bg, white bold, centred, framed
    row  7+    data, framed, with the header frozen and an autofilter on it

What it deliberately does NOT add is a GRAND TOTAL row. The SME sheets carry
one because their numeric columns are all quantities in a known unit; a generic
report's numeric columns are things like `Days_Overdue` and `Unit_Price`, and
summing those would print a confident wrong number.
"""
from __future__ import annotations

import io
import os
from datetime import datetime
from decimal import Decimal

from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

# Shared with the xlsxwriter layouts so both paths render the same palette.
from .sme_export_layouts import COLOR_SCHEMES, _LOGO_PATH

TITLE_ROW = 5      # 1-based: rows 1-4 are the logo + meta band
HEADER_ROW = 6
DATA_ROW = 7

_THIN = Side(style="thin", color="D0D5DD")
_BORDER = Border(left=_THIN, right=_THIN, top=_THIN, bottom=_THIN)


def _hex(c: str) -> str:
    """'#1A2A3A' → '1A2A3A' (openpyxl wants no leading hash)."""
    return str(c).lstrip("#").upper()


def xl_val(v):
    """Coerce to something openpyxl can write, preserving numeric types so the
    cell stays a number in Excel rather than becoming text."""
    if v is None:
        return ""
    if isinstance(v, bool):
        return v
    if isinstance(v, Decimal):
        return float(v)
    if isinstance(v, (int, float, str)):
        return v
    if isinstance(v, datetime):
        return v
    return str(v)


def _insert_logo(ws) -> None:
    """Anchor the GI logo at A1. Decoration only — an unreadable or missing
    file must never cost anyone their export, so every failure is swallowed."""
    if not os.path.exists(_LOGO_PATH):
        return
    try:
        from openpyxl.drawing.image import Image as XLImage
        from PIL import Image as PILImage
        buf = io.BytesIO()
        with PILImage.open(_LOGO_PATH) as im:
            im.convert("RGBA").resize((121, 83), PILImage.Resampling.LANCZOS) \
              .save(buf, format="PNG")
        buf.seek(0)
        img = XLImage(buf)          # a fresh Image per sheet — they are not reusable
        img.width, img.height = 121, 83
        ws.add_image(img, "A1")
    except Exception:  # noqa: BLE001
        pass


def _sheet_name(name: str, used: set[str]) -> str:
    """Excel's 31-char limit, its forbidden characters, and de-duplication."""
    clean = str(name or "Sheet")
    for ch in "[]:*?/\\":
        clean = clean.replace(ch, "-")
    clean = clean[:31] or "Sheet"
    base, n = clean, 2
    while clean in used:
        suffix = f" ({n})"
        clean, n = base[:31 - len(suffix)] + suffix, n + 1
    used.add(clean)
    return clean


def write_premium_sheet(ws, title: str, columns: list, rows: list,
                        username: str, scheme: str = "dashboard") -> None:
    """Render one branded sheet in place. Shared by every entry point below."""
    cs = COLOR_SCHEMES.get(scheme, COLOR_SCHEMES["dashboard"])
    columns = list(columns)
    n_cols = max(len(columns), 1)

    _insert_logo(ws)
    for r in range(1, 5):
        ws.row_dimensions[r].height = 16

    # Meta band — right-aligned into the last two columns, as the SME sheets do.
    if n_cols >= 2:
        lab = Font(size=8, bold=True, color="555555")
        val = Font(size=8, color="333333")
        for row, (k, v) in enumerate(
                (("Report Generated:", datetime.now().strftime("%Y-%m-%d  %H:%M")),
                 ("Generated By:", username or "GI Hub")), start=2):
            c1 = ws.cell(row=row, column=n_cols - 1, value=k)
            c1.font, c1.alignment = lab, Alignment(horizontal="right", vertical="center")
            c2 = ws.cell(row=row, column=n_cols, value=v)
            c2.font, c2.alignment = val, Alignment(horizontal="left", vertical="center")

    # Title bar.
    tc = ws.cell(row=TITLE_ROW, column=1, value=str(title or ""))
    tc.font = Font(bold=True, size=13, color="FFFFFF")
    tc.fill = PatternFill("solid", fgColor=_hex(cs["title_bg"]))
    tc.alignment = Alignment(horizontal="center", vertical="center")
    if n_cols > 1:
        ws.merge_cells(start_row=TITLE_ROW, start_column=1,
                       end_row=TITLE_ROW, end_column=n_cols)
    ws.row_dimensions[TITLE_ROW].height = 22

    # Header row.
    hf = Font(bold=True, size=10, color="FFFFFF")
    hfill = PatternFill("solid", fgColor=_hex(cs["header_bg"]))
    halign = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for i, col in enumerate(columns, 1):
        c = ws.cell(row=HEADER_ROW, column=i, value=str(col))
        c.font, c.fill, c.alignment, c.border = hf, hfill, halign, _BORDER
    ws.row_dimensions[HEADER_ROW].height = 18

    # Data.
    df = Font(size=9)
    dalign = Alignment(vertical="center")
    for ri, row in enumerate(rows):
        for ci in range(1, len(columns) + 1):
            v = row[ci - 1] if ci - 1 < len(row) else None
            c = ws.cell(row=DATA_ROW + ri, column=ci, value=xl_val(v))
            c.font, c.border, c.alignment = df, _BORDER, dalign

    if columns:
        last = get_column_letter(len(columns))
        ws.auto_filter.ref = f"A{HEADER_ROW}:{last}{HEADER_ROW + len(rows)}"
    ws.freeze_panes = f"A{DATA_ROW}"

    # Column widths from the widest sampled content (first 300 rows).
    for i, col in enumerate(columns, 1):
        widest = len(str(col))
        for r in rows[:300]:
            if i - 1 < len(r):
                widest = max(widest, len(str(xl_val(r[i - 1]))))
        ws.column_dimensions[get_column_letter(i)].width = min(max(widest + 3, 11), 46)


def premium_xlsx_sheets(sheets: list, username: str, *,
                        scheme: str = "dashboard") -> bytes:
    """`sheets` = [(sheet_title, columns, rows)] → branded multi-sheet workbook.

    Each sheet's own title doubles as its title bar, matching how the SME
    workbooks name their sections.
    """
    from openpyxl import Workbook
    wb = Workbook()
    wb.remove(wb.active)
    used: set[str] = set()
    for sheet_title, columns, rows in (sheets or [("Report", [], [])]):
        ws = wb.create_sheet(title=_sheet_name(sheet_title, used))
        write_premium_sheet(ws, str(sheet_title or "Report"), columns,
                            list(rows), username, scheme)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def premium_xlsx(title: str, columns: list, rows: list, username: str, *,
                 scheme: str = "dashboard") -> bytes:
    """Single-sheet branded workbook — the one-section case."""
    return premium_xlsx_sheets([(str(title or "Report"), columns, rows)],
                               username, scheme=scheme)
