"""A delivery note leaves the warehouse with its paperwork, or it does not leave

Revision ID: b4f21c8ea9d7
Revises: a3c17e9b25d4
Create Date: 2026-08-13

THE GAP

`ship_dn` took no arguments. A warehouse user clicked Ship, the DN flipped to
`in_transit`, and a truck left with goods whose physical delivery note existed
only on paper in the cab. When it arrived, the site store keeper had a system
record and a piece of paper with no relationship to each other: the DN_Number
in the app is generated by the app, and the number printed on the vendor's or
the carrier's document is a different string entirely. Reconciling a disputed
delivery meant a phone call.

So shipping now REQUIRES two things, and this revision is where they live:

  `dn_document_no`   the number on the physical document. Free text, because
                     it is somebody else's numbering scheme — carriers and
                     vendors do not share ours.
  `dn_attachment_id` the scanned document itself, in `entry_attachments`
                     (doc_type `delivery_note`). That table already owns the
                     BLOB handling, the 15 MB cap, the MIME allowlist, the
                     site scoping and the uploader-only delete; a second
                     document table would have to re-earn all five.

NULLABLE, AND THAT IS DELIBERATE

Both columns are nullable and no backfill is attempted. Every DN shipped
before today went out without this paperwork — that is a fact about the past,
and inventing a value for it would put a number in a field that means "this
is what the driver was carrying" when nobody knows what the driver was
carrying. The gate is enforced going forward, in `ship_dn`, where a NULL can
still be refused; a NOT NULL constraint here would have forced a fiction into
203 historical rows to satisfy a rule that did not exist when they shipped.

WHY NOT REUSE THE MTC UPLOAD

An MTC certifies the MATERIAL and is inherited down the chain (PO → DN →
warehouse → site) precisely so nobody uploads it twice. A delivery note
records THIS SHIPMENT and is inherited by nothing. They answer different
questions and travel differently, so they are stored differently. The MTC
upload at ship time stays exactly as optional as it was.
"""
from alembic import op
import sqlalchemy as sa

revision = "b4f21c8ea9d7"
down_revision = "a3c17e9b25d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("delivery_notes", sa.Column("dn_document_no", sa.Text(), nullable=True))
    op.add_column("delivery_notes", sa.Column("dn_attachment_id", sa.Integer(), nullable=True))
    op.add_column("delivery_notes", sa.Column("shipped_at", sa.DateTime(), nullable=True))
    op.add_column("delivery_notes", sa.Column("shipped_by", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("delivery_notes", "shipped_by")
    op.drop_column("delivery_notes", "shipped_at")
    op.drop_column("delivery_notes", "dn_attachment_id")
    op.drop_column("delivery_notes", "dn_document_no")
